services:
  _defaults:
    autowire: true
    autoconfigure: true

  Reindeer\SymfonyMiddleware\EventSubscriber\MiddlewareSubscriber:
    arguments:
      $middlewareList: !tagged_iterator { tag: 'reindeer_middleware', index_by: 'alias' }
    tags:
      - { name: 'kernel.event_subscriber' }

  Reindeer\SymfonyMiddleware\Contracts\RequestHandlerInterface: '@Reindeer\SymfonyMiddleware\Middleware\RequestHandler'
  Reindeer\SymfonyMiddleware\Middleware\RequestHandler: ~

  Reindeer\SymfonyMiddleware\Contracts\ResponseInterface: '@Symfony\Component\HttpFoundation\Response'
  Reindeer\SymfonyMiddleware\Contracts\RequestInterface: '@Symfony\Component\HttpFoundation\Request'
